# Usa un'immagine base di Python
FROM python:3.11.7

# Imposta la directory di lavoro all'interno del container
WORKDIR /app

# Copia il contenuto della directory corrente nel container
COPY fog_node.py /app/

# Verifica che il file fog_node.py sia copiato correttamente
RUN ls /app

# Installa le librerie necessarie
RUN pip install --no-cache-dir paho-mqtt
RUN pip install --no-cache-dir requests

# Esponi le porte di Mosquitto
EXPOSE 8883

# Comando per eseguire il programma Python quando il container parte
CMD ["python", "-u","fog_node.py"]
